INCLUDE(${OE_CURRENT_EXTENSION_DIR}/FindMathGL.cmake)

IF (MATHGL_FOUND)
  INCLUDE_DIRECTORIES(${MATHGL_INCLUDE_DIR})
ELSE (MATHGL_FOUND)
   MESSAGE ("WARNING: Could not find MATHGL - depending targets will be disabled.")
   SET(OE_MISSING_LIBS "${OE_MISSING_LIBS}, MathGL")
ENDIF(MATHGL_FOUND)
